import { generateUtilityClass, generateUtilityClasses } from '@mui/utils';

/**
 * File Explorer utility classes.
 *
 * @interface FileExplorerClasses
 */
export interface FileExplorerClasses {
  /**
   * Styles applied to the root element.
   */
  root: string;
}

/**
 * Key of a file explorer class.
 *
 * @typedef {string} FileExplorerClassKey
 * @extends keyof FileExplorerClasses
 */

export type FileExplorerClassKey = keyof FileExplorerClasses;

/**
 * Retrieves the utility class for a file explorer component.
 *
 * @param {string} slot - The slot to retrieve the utility class for.
 * @returns {string} The utility class for the specified slot.
 */
export function getFileExplorerUtilityClass(slot: string): string {
  return generateUtilityClass('MuiFileExplorer', slot);
}

/**
 * File Explorer classes generated by MUI's utility class generator.
 *
 * @typedef {Object<string, string>} FileExplorerClasses
 * @property {string} root - Styles applied to the root element.
 */
export const fileExplorerClasses: FileExplorerClasses = generateUtilityClasses('MuiFileExplorer', [
  'root',
]);