extends: existence
message: We avoid referencing the company name '%s'. Instead you can reference a product or the team.
level: warning
ignorecase: false
tokens:
  - 'MUI \w+'
exceptions:
  - 'MUI X'
  - 'MUI X'
  - 'MUI System'
  - 'MUI System'
