extends: substitution
message: Do you mean '%s' instead of '%s'?
level: warning
ignorecase: true
# swap maps tokens in form of bad: good
# for more information: https://vale.sh/docs/topics/styles/#substitution
swap:
  bellow: below
