packages:
  - benchmark
  - packages/*
  - packages-internal/*
  - docs
  - api
  - infra
  - test
onlyBuiltDependencies:
  - '@nestjs/core'
  - aws-sdk
  - core-js
  - esbuild
  - mongodb-memory-server
  - msgpackr-extract
  - nx
  - puppeteer
  - sharp
