/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MONGODB_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ROOT_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendSms": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Subscribe": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Verify": {
      "name": string
      "type": "sst.aws.Function"
    }
    "stoked-uicomStaticSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}