/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MONGODB_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ROOT_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendSms": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Subscribe": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Verify": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}