/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_color_free: (a: number, b: number) => void;
export const __wbg_get_color_a: (a: number) => number;
export const __wbg_get_color_b: (a: number) => number;
export const __wbg_get_color_g: (a: number) => number;
export const __wbg_get_color_r: (a: number) => number;
export const __wbg_previewrenderer_free: (a: number, b: number) => void;
export const __wbg_set_color_a: (a: number, b: number) => void;
export const __wbg_set_color_b: (a: number, b: number) => void;
export const __wbg_set_color_g: (a: number, b: number) => void;
export const __wbg_set_color_r: (a: number, b: number) => void;
export const benchmark_composition: (a: number, b: number, c: number, d: number) => void;
export const color_new: (a: number, b: number, c: number, d: number) => number;
export const color_rgb: (a: number, b: number, c: number) => number;
export const previewrenderer_cache_image: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const previewrenderer_clear: (a: number) => void;
export const previewrenderer_clear_image_cache: (a: number) => void;
export const previewrenderer_get_metrics: (a: number, b: number) => void;
export const previewrenderer_is_image_cached: (a: number, b: number, c: number) => number;
export const previewrenderer_new: (a: number, b: number, c: number, d: number) => void;
export const previewrenderer_render_frame: (a: number, b: number, c: number, d: number) => void;
export const previewrenderer_render_frame_at_time: (a: number, b: number, c: number, d: number, e: number) => void;
export const init: () => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
