export default {
  gender: [
    'male',
    'female',
    'non-binary',
  ],
  bodyType: [
    'Slim',
    'Athletic',
    'Average',
    'Curvy',
    'A Few Extra Pounds',
    'Full / Overweight'
  ],
  ethnicity : [
    'Asian',
    'Black / African Descent',
    'Latin / Hispanic',
    'East Indian',
    'Middle Eastern',
    'Mixed',
    'Native American',
    'Pacific Islander',
    'White / Caucasian',
    'Other',
  ],
  hairColor: [
    'Auburn',
    'Black',
    'Blonde',
    'Light Brown',
    'Dark Brown',
    'Grey',
    'Red',
    'White',
    'Other',
  ],
  smoking: [
    'Non Smoker',
    'Light Smoker',
    'Heavy Smoker',
  ],
  vaping: [
    'Non Vaper',
    'Light Vaper',
    'Constant Vaper',
  ],
  drinking: ['Non Drinker', 'Social Drinker', 'Heavy Drinker'],
  relationship: [
    'Single',
    'Divorced',
    'Separated',
    'Married But Looking',
    'Open Relationship',
    'Widowed',
  ],
  education: [
    'High School',
    'Some College',
    'Associates Degree',
    'Bachelors Degree',
    'Graduate Degree',
    'PhD / Post Doctoral',
    'MD / Medical Doctor',
    'JD / Attorney',
  ],
  drugs: [
    'Never',
    '420',
    'Psychedelics',
    'Uppers',
    'Downers',
    'Yes Please'
  ]
}
