/**
 * @fileoverview Provides utility classes for the MUI File Explorer Grid component.
 */

import generateUtilityClass from '@mui/utils/generateUtilityClass';
import generateUtilityClasses from '@mui/utils/generateUtilityClasses';

/**
 * Interface representing the styles applied to the grid headers component.
 */
export interface FileExplorerGridHeadersClasses {
  /**
   * Styles applied to the root element of the grid headers.
   */
  root: string;
  
  /**
   * Styles applied to each column element in the grid headers.
   */
  column: string;
  
  /**
   * Styles applied to the transition component used for grouping elements.
   */
  groupTransition: string;
  
  /**
   * Styles applied to the content container of individual icons.
   */
  iconContainer: string;
  
  /**
   * Styles applied to the label element displaying file names.
   */
  name: string;
}

/**
 * Type representing a key to access the utility classes for the grid headers component.
 */
export type FileExplorerGridHeadersClassKey = keyof FileExplorerGridHeadersClasses;

/**
 * Utility function to retrieve the class name for a specific slot in the MUI File Explorer Grid component.
 *
 * @param {string} slot - The slot name to retrieve the class for.
 * @returns {string} The class name for the specified slot.
 */
export function getFileUtilityClass(slot: string): string {
  return generateUtilityClass('MuiFileExplorerGridHeaders', slot);
}

/**
 * Utility classes generated by MUI's utility class generator.
 */
export const fileExplorerViewGridHeadersClasses: FileExplorerGridHeadersClasses = generateUtilityClasses('MuiFileExplorerGridHeaders', [
  'root',
  'column',
  'groupTransition',
  'iconContainer',
  'name',
]);