packages:
  - 'local-ui-lib'
  - 'zero-runtime-*'
  - '../packages/waterfall'
  - '../packages/docs-utils'
  - '../packages/test-utils'
  - '../packages-internal/*'
  - '../packages/mui-*'
  - '../packages/zero-*'
