import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses';
import { PLAYBOOKS } from './playbooks';
import type { AuditLeadRecord, AuditReport } from './types';

/**
 * Emails the completed audit report to the lead — the one piece of the funnel
 * where the visitor walks away with a branded artifact. Sent best-effort from
 * /api/audit/save-lead once the visitor shares an email; Brian is BCC'd so the
 * follow-up thread starts in his inbox, not just in Telegram.
 *
 * Uses the same SES pattern as products/feedbackStore.ts. Silent no-op when
 * SES isn't configured — the lead is still saved and Telegram still fires.
 */

const sesClient = new SESClient({ region: process.env.AWS_REGION || 'us-east-1' });
const sesFromEmail = process.env.SES_FROM_EMAIL || 'noreply@stokd.cloud';
const reportBccEmail = process.env.AUDIT_REPORT_BCC_EMAIL || '';

export interface RenderedAuditEmail {
  subject: string;
  text: string;
  html: string;
}

export interface RenderAuditReportEmailOptions {
  calendlyUrl?: string;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

interface ReportLine {
  title: string;
  meta: string;
  body: string;
}

function reportLines(report: AuditReport): ReportLine[] {
  if (report.playbook === 'ai-readiness') {
    return report.top_opportunities.map((o) => ({
      title: `${o.rank}. ${o.title}`,
      meta: `~${o.hours_saved_per_month} hrs/mo · ${o.effort} · ${o.rough_cost_band}`,
      body: `${o.what_it_does} ${o.why_now} Caveat: ${o.risk_or_caveat}`,
    }));
  }
  if (report.playbook === 'cloud-cost') {
    return report.top_opportunities.map((o) => ({
      title: `${o.rank}. ${o.title}`,
      meta: `${o.monthly_savings_band}/mo · ${o.effort} · risk: ${o.risk_level}`,
      body: `${o.what_it_is} ${o.implementation_steps} Caveat: ${o.caveat}`,
    }));
  }
  return report.top_findings.map((f) => ({
    title: `${f.rank}. [${f.severity.toUpperCase()}] ${f.title}`,
    meta: `${f.effort} · ${f.cost_band}${f.blocks_compliance ? ' · blocks compliance' : ''}`,
    body: `${f.what_it_is} ${f.why_it_matters} Fix: ${f.fix_action}`,
  }));
}

function reportHeadline(report: AuditReport): string {
  if (report.playbook === 'ai-readiness') {
    return `Readiness: ${report.readiness} — ${report.readiness_reason}`;
  }
  if (report.playbook === 'cloud-cost') {
    return `${report.cloud.toUpperCase()} · spend ${report.spend_tier} · est. savings ${report.estimated_savings_band}`;
  }
  return `Posture: ${report.current_posture} · compliance pressure: ${report.compliance_pressure}`;
}

/**
 * Pure renderer — returns null when the lead has no report yet (nothing worth
 * emailing). Kept side-effect free so it is unit-testable without SES.
 */
export function renderAuditReportEmail(
  lead: AuditLeadRecord,
  options: RenderAuditReportEmailOptions = {},
): RenderedAuditEmail | null {
  const { report } = lead;
  if (!report) {
    return null;
  }
  const label = PLAYBOOKS[report.playbook]?.label ?? report.playbook;
  const company = report.company || lead.company || 'your business';
  const greeting = lead.name ? `Hi ${lead.name},` : 'Hi,';
  const lines = reportLines(report);
  const calendly = options.calendlyUrl || process.env.NEXT_PUBLIC_CALENDLY_URL || '';

  const subject = `Your ${label} — ${company}`;

  const textParts: string[] = [
    greeting,
    '',
    `Here's the ${label} you just ran for ${company} — yours to keep.`,
    '',
    `${report.one_liner}`,
    reportHeadline(report),
    '',
    ...lines.flatMap((l) => [l.title, `   ${l.meta}`, `   ${l.body}`, '']),
    `What Brian would do first: ${report.what_brian_would_do_first}`,
    '',
    `Honest caveat: ${report.honest_caveat}`,
    '',
    `Next step: ${report.next_step}`,
  ];
  if (calendly) {
    textParts.push('', `Book a free 30-minute call: ${calendly}`);
  }
  textParts.push(
    '',
    '— Brian Stoker · Stoked Consulting · https://consulting.stokd.cloud',
    'This report was generated by an AI agent Brian built; he reviews every one personally before following up.',
    "You're receiving this single email because you ran this audit and asked for the report — there's no mailing list. Reply \"no thanks\" and Brian won't contact you again.",
  );
  const text = textParts.join('\n');

  const htmlLines = lines
    .map(
      (l) => `
      <tr><td style="padding:12px 0;border-bottom:1px solid #e5e7eb;">
        <div style="font-weight:700;color:#111827;">${escapeHtml(l.title)}</div>
        <div style="color:#3399ff;font-size:13px;margin:2px 0;">${escapeHtml(l.meta)}</div>
        <div style="color:#4b5563;font-size:14px;line-height:1.5;">${escapeHtml(l.body)}</div>
      </td></tr>`,
    )
    .join('');

  const html = `<!DOCTYPE html>
<html><body style="margin:0;padding:24px;background:#f9fafb;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid #e5e7eb;border-radius:12px;">
    <tr><td style="padding:28px;">
      <div style="font-size:12px;letter-spacing:2px;color:#3399ff;font-weight:700;">STOKED CONSULTING</div>
      <h1 style="font-size:20px;color:#111827;margin:8px 0 4px;">${escapeHtml(label)} — ${escapeHtml(company)}</h1>
      <p style="color:#4b5563;font-size:14px;margin:4px 0 16px;">${escapeHtml(report.one_liner)}<br/><strong>${escapeHtml(reportHeadline(report))}</strong></p>
      <p style="color:#111827;font-size:14px;">${escapeHtml(greeting)} here's the report you just ran — yours to keep.</p>
      <table role="presentation" width="100%">${htmlLines}</table>
      <p style="color:#111827;font-size:14px;margin-top:16px;"><strong>What Brian would do first:</strong> ${escapeHtml(report.what_brian_would_do_first)}</p>
      <p style="color:#6b7280;font-size:13px;"><em>Honest caveat: ${escapeHtml(report.honest_caveat)}</em></p>
      ${calendly ? `<p style="margin:20px 0;"><a href="${escapeHtml(calendly)}" style="background:#3399ff;color:#ffffff;text-decoration:none;padding:10px 18px;border-radius:8px;font-weight:700;font-size:14px;">Book a free 30-minute call</a></p>` : ''}
      <p style="color:#9ca3af;font-size:12px;margin-top:24px;">— Brian Stoker · <a href="https://consulting.stokd.cloud" style="color:#3399ff;">consulting.stokd.cloud</a><br/>
      Generated by an AI agent Brian built; he reviews every report personally before following up.<br/>
      You&#39;re receiving this single email because you ran this audit and asked for the report — there&#39;s no mailing list. Reply &quot;no thanks&quot; and Brian won&#39;t contact you again.</p>
    </td></tr>
  </table>
</body></html>`;

  return { subject, text, html };
}

/**
 * Send the rendered report to the lead. Best-effort: returns true on send,
 * false when skipped (no email / no report) or on SES failure. Never throws —
 * a mail hiccup must not fail the save-lead request.
 */
export async function sendAuditReportEmail(lead: AuditLeadRecord): Promise<boolean> {
  if (!lead.email) {
    return false;
  }
  const rendered = renderAuditReportEmail(lead);
  if (!rendered) {
    return false;
  }
  try {
    await sesClient.send(
      new SendEmailCommand({
        Source: sesFromEmail,
        Destination: {
          ToAddresses: [lead.email],
          ...(reportBccEmail ? { BccAddresses: [reportBccEmail] } : {}),
        },
        Message: {
          Subject: { Data: rendered.subject },
          Body: {
            Text: { Data: rendered.text },
            Html: { Data: rendered.html },
          },
        },
      }),
    );
    return true;
  } catch (err) {
    console.error('audit report email failed', err);
    return false;
  }
}
