name: Mark duplicate

on:
  issue_comment:
    types: [created]

permissions: {}

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: mark-duplicate
        uses: actions-cool/issues-helper@d5f2de3db22134219ada6d57ac183bf6280d0ce8 # v3.5.0
        with:
          actions: 'mark-duplicate'
          token: ${{ secrets.GITHUB_TOKEN }}
          duplicate-labels: 'duplicate'
          remove-labels: 'status: incomplete,status: needs triage'
          close-issue: true
